name: Simple txt artifact

on:
  workflow_dispatch: # Manual trigger

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Create a file
      run: |
        echo "Current date: " $(date +'%d/%m/%Y %H:%M:%S') > current_date.txt
    - name: Archive file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: current_date_artifact
        path: current_date.txt
