name: Display OS

on:
  workflow_dispatch: # Manual trigger

jobs:
  display-env-info:
    runs-on: ubuntu-latest

    steps:
    - name: Print OS on console
      run: |
        echo "Running job on: ${{ runner.os }}"
